# Generated by roxyassert: do not edit by hand.
# Re-generated on devtools::document(). Commit this file like NAMESPACE.

assert_args_AisStream__initialize <- function(api_key, bounding_boxes, message_types, ship_mmsi, stale_timeout) {
  assert_scalar_character(api_key)
  assert_list(bounding_boxes)
  if (!is.null(message_types)) {
    assert_character(message_types)
    assert_no_missing_values(message_types)
  }
  if (!is.null(ship_mmsi)) {
    assert_character(ship_mmsi)
    assert_no_missing_values(ship_mmsi)
  }
  assert_scalar_double(stale_timeout)
  assert_between(stale_timeout, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_AisStream__initialize <- function(value) {
  assert_class(value, "AisStream")
  return(value)
}

assert_args_AisStream__update_subscription <- function(bounding_boxes, message_types, ship_mmsi) {
  if (!is.null(bounding_boxes)) {
    assert_list(bounding_boxes)
  }
  if (!is.null(message_types)) {
    assert_character(message_types)
    assert_no_missing_values(message_types)
  }
  if (!is.null(ship_mmsi)) {
    assert_character(ship_mmsi)
    assert_no_missing_values(ship_mmsi)
  }
  return(invisible(NULL))
}

assert_return_AisStream__update_subscription <- function(value) {
  assert_class(value, "AisStream")
  return(value)
}

assert_return_AisStream__subscription_frame <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_parse_go_time <- function(x) {
  return(invisible(NULL))
}

assert_return_parse_go_time <- function(value) {
  assert_class(value, "POSIXct")
  return(value)
}

assert_args_parse_ais <- function(raw) {
  assert_scalar_character(raw)
  return(invisible(NULL))
}

assert_return_parse_ais <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_ais_metadata <- function(parsed) {
  assert_list(parsed)
  return(invisible(NULL))
}

assert_return_ais_metadata <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("message_type", "mmsi", "ship_name", "latitude", "longitude", "time_utc"))
  assert_character(value[["message_type"]])
  assert_character(value[["mmsi"]])
  assert_character(value[["ship_name"]])
  assert_double(value[["latitude"]])
  assert_double(value[["longitude"]])
  assert_datetime(value[["time_utc"]])
  return(value)
}

assert_args_as_position_report <- function(parsed) {
  assert_list(parsed)
  return(invisible(NULL))
}

assert_return_as_position_report <- function(value) {
  assert_data_table(value)
  assert_has_columns(value, c("message_type", "mmsi", "ship_name", "latitude", "longitude", "time_utc", "sog", "cog", "true_heading", "nav_status", "rate_of_turn"))
  assert_character(value[["message_type"]])
  assert_character(value[["mmsi"]])
  assert_character(value[["ship_name"]])
  assert_double(value[["latitude"]])
  assert_double(value[["longitude"]])
  assert_datetime(value[["time_utc"]])
  assert_double(value[["sog"]])
  assert_double(value[["cog"]])
  assert_double(value[["true_heading"]])
  assert_double(value[["nav_status"]])
  assert_double(value[["rate_of_turn"]])
  return(value)
}

assert_args_normalise_bounding_box <- function(box) {
  assert_list(box)
  return(invisible(NULL))
}

assert_return_normalise_bounding_box <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_normalise_bounding_boxes <- function(bounding_boxes) {
  assert_list(bounding_boxes)
  return(invisible(NULL))
}

assert_return_normalise_bounding_boxes <- function(value) {
  assert_list(value)
  return(value)
}

assert_args_build_subscription <- function(api_key, bounding_boxes, message_types, ship_mmsi) {
  assert_scalar_character(api_key)
  assert_list(bounding_boxes)
  if (!is.null(message_types)) {
    assert_character(message_types)
    assert_no_missing_values(message_types)
  }
  if (!is.null(ship_mmsi)) {
    assert_character(ship_mmsi)
    assert_no_missing_values(ship_mmsi)
  }
  return(invisible(NULL))
}

assert_return_build_subscription <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_ndjson_hour_path <- function(dir, at) {
  assert_scalar_character(dir)
  assert_class(at, "POSIXct")
  return(invisible(NULL))
}

assert_return_ndjson_hour_path <- function(value) {
  assert_scalar_character(value)
  return(value)
}

assert_args_ndjson_sink <- function(dir, flush_seconds) {
  assert_scalar_character(dir)
  assert_scalar_double(flush_seconds)
  assert_between(flush_seconds, lower = 0, lower_inclusive = FALSE, upper = Inf, upper_inclusive = FALSE)
  return(invisible(NULL))
}

assert_return_ndjson_sink <- function(value) {
  assert_function(value)
  return(value)
}

